### ISSUE TITLE
[style] Avoid using import * while importing modules

### ISSUE THREAD

**Issue by RainrainWu** [ccns/CCNSAnime_ffmpeg_pool#1]
盡量避免用 `import *`，原因是

1. Python 精神之一：Explicit is better than implicit
2. import 一堆不必要的東西浪費資源
3. 你不知道 import 進來的東西會不會撞到 identifier，比如兩個 module 都有 `env` 這個 object，當你 import * 的時候可能就會被 re-assign 了，但你沒注意到

## Ref
[Importing `*` in Python](https://s16h.medium.com/importing-star-in-python-88fe9e8bd4d2)

**Comment by RainrainWu** [comment]
- https://github.com/ccns/CCNSAnime_ffmpeg_pool/blob/master/tasks.py#L1
- https://github.com/ccns/CCNSAnime_ffmpeg_pool/blob/master/app.py#L3

**Comment by a20034294** [comment]
It make sense, thanks
