### ISSUE TITLE
[design] Environment variables should be read only once

### ISSUE THREAD

**Issue by RainrainWu** [ccns/CCNSAnime_ffmpeg_pool#3]
環境變數應該只被單一 module 讀取一次，存成變數後提供給其他 module 讀取，原因是：

- 每次都 call 函數讀 env 浪費資源
- Python 每個 Module 執行的時間點不同，沒做好隔離的話可能同個 env variable 讀到不同的 value

**Comment by a20034294** [comment]
我看起來只有被 load 一次 你會看到兩個的原因是因為需要單獨啟動 celery worker 而 worker 也需要讀 env

**Comment by RainrainWu** [comment]
I think an independent `config.py` would be better in this case for higher cohesion, but it is just my personal opinion.
The original method seems to be fine.
