### ISSUE TITLE
[design] Error handling for external operation

### ISSUE THREAD

**Issue by RainrainWu** [ccns/CCNSAnime_ffmpeg_pool#5]
用 `os.system` 直接跑 script 可能會出錯，建議做一下 error handling，也在 flask 的 handler 做一下，方便使用者知道出了什麼錯

- https://github.com/ccns/CCNSAnime_ffmpeg_pool/blob/master/Task/anime_create.py#L18
- https://github.com/ccns/CCNSAnime_ffmpeg_pool/blob/master/app.py#L17

**Comment by a20034294** [comment]
這個確實得做 但特別麻煩
我還打算做進度跟狀態查詢
應該會一起做

**Comment by RainrainWu** [comment]
好歐～ 我只是看到稍微提一下怕忘記

**Comment by a20034294** [comment]
阿我好像不小心就已經修掉了
